/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: bird (https://sketchfab.com/birdii)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bunny-detective-b2ab08f1f5d04d9182400735d6471368
Title: Bunny Detective
*/

import { useEffect, useRef } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

import bunnyScene from "../assets/3d/bunny_detective.glb";

const Bunny = ({ radius, speed, scale, ...props }) => {
  const group = useRef();
  const { scene, nodes, materials, animations } = useGLTF(bunnyScene);
  const { actions } = useAnimations(animations, group);
  const angle = useRef(0);

  useEffect(() => {
    actions["Walk"].play();
    // Apply rotation to the group
  }, [actions]);
  useFrame(() => {
    angle.current += speed;
    const z = radius * Math.cos(angle.current);
    const x = radius * Math.sin(angle.current);
    const nextZ = radius * Math.cos(angle.current + speed);
    const nextX = radius * Math.sin(angle.current + speed);

    group.current.position.set(x, -0.6, z);
    const lookAtVector = new THREE.Vector3(nextX, 0, nextZ);
    group.current.lookAt(lookAtVector);
  });
  return (
    <group ref={group} scale={scale} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_39">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Bunny}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.Whiskers}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <group name="Bunny_38" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Bunny;
