/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jokim (https://sketchfab.com/Joaquim.Falo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nekomori-frog-statue-2beb5e8353ad415a9b166b9793338895
Title: Nekomori Frog Statue
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import scene from "../assets/3d/frog_statue.glb";

const Frog = ({ scale, currentAnimation, ...props }) => {
  const { nodes, materials } = useGLTF(scene);
  const group = useRef();
  return (
    <group {...props} scale={scale} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.729, -0.269]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["frog_Material_#3_0"].geometry}
              material={materials.Material_3}
              position={[0, 0.003, 0.369]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            {/* <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box001__0.geometry}
              material={materials.Object010__0}
              position={[0, 0, -10]}
            /> */}
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Object008_Material_#4_0"].geometry}
            material={materials.Material_4}
            position={[0, 0.473, -2.145]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object010__0.geometry}
            material={materials.Object010__0}
            position={[0, 0.473, -2.145]}
          />
        </group>
      </group>
    </group>
  );
};

export default Frog;
