/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: cuadot (https://sketchfab.com/cuadot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mailbox-phone-f1dacc2627224cbe9ec4bfb57fc5b6cf
Title: MailBox Phone!
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import scene from "../assets/3d/telephone.glb";

const MailboxPhone = ({ scale, currentAnimation, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);
  /*   useEffect(() => {
    actions["Scene"].play();
    console.log(actions);
  }, []); */

  return (
    <group {...props} scale={scale} dispose={null}>
      <group scale={1.307}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials["Material.012"]}
        />
        <group position={[-0.133, 2.399, -0.05]} scale={0.806}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials["Material.008"]}
          />
          <group
            position={[-0.785, 0.812, 0]}
            rotation={[0, 0, -Math.PI / 5]}
            scale={0.443}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_13.geometry}
              material={materials["Material.009"]}
              position={[-0.038, 0, 0]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={0.934}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_15.geometry}
              material={materials["Material.011"]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={0.915}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_17.geometry}
              material={materials["Material.009"]}
              position={[-0.038, 0, 0]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.46, 0.102, 0.46]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_19.geometry}
              material={materials["Material.009"]}
              position={[-0.038, 0, 0]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={0.481}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials["Material.008"]}
            position={[-0.279, -0.248, -3.611]}
            scale={0.035}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials["Material.008"]}
            position={[0, 1.489, 0]}
            scale={[0.402, 0.43, 0.378]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_21.geometry}
            material={materials["Material.009"]}
            position={[-0.904, 0.709, 0.383]}
            rotation={[1.844, -0.628, -1.408]}
            scale={[0.025, 0.033, 0.023]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_7.geometry}
            material={materials["Material.009"]}
            position={[0, 1.278, -0.025]}
            scale={[0.047, 0.069, 0.047]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_25.geometry}
            material={materials["Material.010"]}
            position={[0.754, 0.041, -0.768]}
            scale={0.125}
          />
        </group>
      </group>
    </group>
  );
};

export default MailboxPhone;
