/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Natural History Museum of Los Angeles County (https://sketchfab.com/NHMLA)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-raccoon-procyon-lotor-0e494f866fc24ab3ae2d8fe02b1d6110
Title: Low poly raccoon (Procyon lotor)
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import scene from "../assets/3d/raccoon_mascot.glb";

const RacoonMascot = ({ scale, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Armature|Idle"].play();
    //console.log(actions);
  }, []);
  return (
    <group ref={group} scale={scale} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="87a940c7c1d747148d7e9a966bd27f2dfbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="RaccoonBase" rotation={[-Math.PI / 2, 0, 0]} />
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.BaseMat}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <skinnedMesh
                      name="Object_10"
                      geometry={nodes.Object_10.geometry}
                      material={materials.LineArt}
                      skeleton={nodes.Object_10.skeleton}
                    />
                    <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default RacoonMascot;
