/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: IsaacTheMaverick (https://sketchfab.com/IsaacTheMaverick)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-room-a6bf7976f3ac401e96907aa5b8a0c1c1
Title: Low Poly Room
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import scene from "../assets/3d/study_room.glb";

const Study = ({ scale, ...props }) => {
  const ref = useRef();
  const { nodes, materials } = useGLTF(scene);
  return (
    <group scale={scale} {...props} dispose={null}>
      <group
        position={[1.8, -0.27, -0.3]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_UberTexture_0.geometry}
          material={materials.UberTexture}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_PC_Glass_0.geometry}
          material={materials.PC_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Floor_0.geometry}
          material={materials.Floor}
        />
      </group>
    </group>
  );
};

export default Study;
